# SPDX-FileCopyrightText: 2023 Erlang Ecosystem Foundation
# SPDX-License-Identifier: Apache-2.0

annotations:
  - checks:
      - fuzzing
    reasons:
      - reason: not-applicable # Erlang / Elixir is memory safe
  - checks:
      - packaging
    reasons:
      - reason: not-supported # Using Hex.pm
