# SPDX-FileCopyrightText: 2023 Erlang Ecosystem Foundation
# SPDX-License-Identifier: Apache-2.0

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

permissions:
  contents: read

jobs:
  test:
    name: "Test"

    permissions:
      contents: read
      security-events: write

    uses: ./.github/workflows/part_test.yml
    secrets:
      OID_CERTIFICATION_API_TOKEN: ${{ secrets.OID_CERTIFICATION_API_TOKEN }}

  license:
    name: "License"

    permissions:
      id-token: write
      contents: read
      attestations: write

    uses: ./.github/workflows/part_license.yml
    with:
      attest: false

  docs:
    name: "Docs"

    permissions:
      id-token: write
      contents: read
      attestations: write

    uses: ./.github/workflows/part_docs.yml
    with:
      attest: false

  dependency-review:
    name: "Dependency Review"

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
